//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTcare.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=TC2016_02;Integrated Security=True")]
        public string gnConnHandle {
            get {
                return ((string)(this["gnConnHandle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=TCKE_MM001;Integrated Security=True")]
        public string TCKE_MM001ConnectionString {
            get {
                return ((string)(this["TCKE_MM001ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ITMANAGER1;Initial Catalog=NACCUDATA;User ID=sa;Password=Whatever4999" +
            "!")]
        public string NACCUDATAConnectionString {
            get {
                return ((string)(this["NACCUDATAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-O3EOLPUMEQ6;Initial Catalog=NACCUDATA;User ID=sa;Password=Whateve" +
            "r4999!")]
        public string NACCUDATAConnectionString1 {
            get {
                return ((string)(this["NACCUDATAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ITMANAGER;Initial Catalog=NACCUDATA;User ID=sa;Password=Whatever4999!" +
            "")]
        public string NACCUDATAConnectionString2 {
            get {
                return ((string)(this["NACCUDATAConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ITMANAGER12;Initial Catalog=NA_SOF001;User ID=sa;Password=Whatever499" +
            "9!")]
        public string NA_SOF001ConnectionString {
            get {
                return ((string)(this["NA_SOF001ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.18;Initial Catalog=NA_GRA001;User ID=sa;Password=Whatever49" +
            "99!")]
        public string NA_GRA001ConnectionString {
            get {
                return ((string)(this["NA_GRA001ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.18;Initial Catalog=NA_LIV001;User ID=sa;Password=Whatever49" +
            "99!")]
        public string NA_LIV001ConnectionString {
            get {
                return ((string)(this["NA_LIV001ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.18;Initial Catalog=NA_SOF001;User ID=sa;Password=Whatever49" +
            "99!")]
        public string NA_SOF001ConnectionString1 {
            get {
                return ((string)(this["NA_SOF001ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-JCQ4H20;Initial Catalog=NA_SOF001;Integrated Security=True")]
        public string NA_SOF001ConnectionString2 {
            get {
                return ((string)(this["NA_SOF001ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NACUUG-SVR;Initial Catalog=Testing_Database;User ID=sa;Password=Whate" +
            "ver4999!")]
        public string Testing_DatabaseConnectionString {
            get {
                return ((string)(this["Testing_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.18;Initial Catalog=Testing_Database;User ID=sa;Password=Wha" +
            "tever4999!")]
        public string Testing_DatabaseConnectionString1 {
            get {
                return ((string)(this["Testing_DatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ITMANAGERALA;Initial Catalog=Testing_Database;User ID=sa;Password=Wha" +
            "tever4999!")]
        public string Testing_DatabaseConnectionString2 {
            get {
                return ((string)(this["Testing_DatabaseConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5SLVP01;Initial Catalog=NA_CFF001;User ID=sa;Password=Whateve" +
            "r4999!")]
        public string NA_CFF001ConnectionString {
            get {
                return ((string)(this["NA_CFF001ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-VQ629P0;Initial Catalog=NA_SOF001;Persist Security Info=True;" +
            "User ID=sa;Password=Whatever4999!")]
        public string NA_SOF001ConnectionString3 {
            get {
                return ((string)(this["NA_SOF001ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-B8NSE3T;Initial Catalog=NA_SOF001;User ID=sa;Password=Whateve" +
            "r4999!")]
        public string NA_SOF001ConnectionString4 {
            get {
                return ((string)(this["NA_SOF001ConnectionString4"]));
            }
        }
    }
}
